#!/usr/bin/env bash
# This script installs and sets up a load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown -R "$USER:$USER" /etc/haproxy/
printf %s "
#frontend configuration
frontend http-in
    bind *:80
    default_backend servers
# Backend configuration
backend servers
    balance roundrobin
    server 177469-web-01 54.146.76.224
    server 177469-web-02 100.26.17.167
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
